### ISSUE TITLE
Failing unittests due to location ambiguity of "Pilsen"

### ISSUE THREAD

**Issue by weinshec** [tomasbedrich/pycaching#101]
Due to changes of the geocaching.com **location query API**, the coordinates of "Pilsen" (as used in the unittests) are returned as [[Query]](https://www.geocaching.com/api/geocode?q=Pilsen) which belong to a place with the same name in the USA [(Google Maps)](https://www.google.com/maps/place/Pilsen,+Wisconsin+54217,+USA/@44.4436563,-87.7264409,17z/data=!3m1!4b1!4m13!1m7!3m6!1s0x0:0x0!2zNDTCsDI2JzM3LjAiTiA4N8KwNDMnMzAuMyJX!3b1!8m2!3d44.44361!4d-87.72509!3m4!1s0x8802d98fcebcbceb:0x8ff682662f0644a8!8m2!3d44.4430662!4d-87.7243415)

However, due to this ambiguity, the following unittests fail

unittest | according cassette
----------| ------------------------
`test.test_geo.TestPoint.test_from_location` | `geo_location_existing.json`
`test.test_geocaching.TestShortcuts.test_geocode` | `geocaching_shortcut_geocode.json`

I'm not sure whether this should be fixed (e.g. by chosing a different city as test query) or not, since it just concerns the unittests. What's your opinion?

**Comment by tomasbedrich** [comment]
Thanks for your report. Lets fix this to have unittests clear. ;)
