### ISSUE TITLE
Get logdate for my_logs()

### ISSUE THREAD

**Issue by S0S-90** [tomasbedrich/pycaching#119]
In my fork I have changed the function my_logs() so that it not only returns the cache but also the date when the user has found (or attended or whatever) it. Are you interested in including this change? If yes, I could try to get the tests running again and send a pull request.

**Comment by tomasbedrich** [comment]
I think it may be interesting feature for someone. We just must think of being either backwards compatible or release a new major version. I would prefer the former solution but don't have any idea how to code it.

**Comment by S0S-90** [comment]
I could imagine that we could make it backards compatible if the logdate is stored inside the found cache itself. For this the Cache class would just an additional attribute 'logdate' which is filled by the function my_logs().

**Comment by tomasbedrich** [comment]
Yes, it could work. I would prefer `visited` to be consistent with naming inside `Log` class.

In next mayor version I could imagine some refactoring – it may be closer to reality to yield `Log` objects with relationship to `Cache` from `my_logs()`. All the required fields would also fit into this solution nicely.

**Comment by S0S-90** [comment]
see pull request #120 

The logdate is now saved in attribute 'visited' in class Cache.
