### ISSUE TITLE
Lowercase coordinates incorrectly converted in Point.from_string()

### ISSUE THREAD

**Issue by twlare** [tomasbedrich/pycaching#122]
In geo.py, the from_string() method of Point accepts a coordinate string and converts it to decimal degrees. When the input string uses lowercase for south or west, the conversion ends up in the wrong hemisphere. An input of "N32 46.000 W111 38.555" returns a correct result. An input of "N32 46.000 w111 38.555" returns the equivalent of N32 46.000 E111 38.555. This is because the hemisphere test is performed on the input string using comparisons of uppercase 'S' and 'W'. The simplest fix might be to convert the input string to uppercase at the beginning of the method. For example:
        # Make it uppercase for consistency
        string = string.upper() # convert to uppercase to simplify hemisphere comparisons
        coords = string.replace("N", " ").replace("S", " ") \
            .replace("E", " ").replace("W", " ").replace("+", " ")

It might be a good idea to add this to the test suite to ensure that the conversion remains correct.

**Comment by tomasbedrich** [comment]
It seems like a good idea to me. Can you create a pull request?
