### ISSUE TITLE
Error loading PMOC as a basic member

### ISSUE THREAD

**Issue by solaristhesun** [tomasbedrich/pycaching#129]
It seems geocaching.search() does not really work if you use a higher limit than 50.

I am getting:

```
Traceback (most recent call last):
  File "/home/sts/.local/lib/python3.6/site-packages/pycaching/util.py", line 26, in wrapper
    return func(*args, **kwargs)
  File "/home/sts/.local/lib/python3.6/site-packages/pycaching/cache.py", line 386, in size
    return self._size
AttributeError: 'Cache' object has no attribute '_size'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sts/.local/lib/python3.6/site-packages/pycaching/cache.py", line 668, in load
    self.wp = root.title.string.split(" ")[0]
  File "/home/sts/.local/lib/python3.6/site-packages/pycaching/cache.py", line 221, in wp
    raise errors.ValueError("GC code '{}' doesn't start with 'GC'.".format(wp))
pycaching.errors.ValueError: GC code 'GEOCACHING' doesn't start with 'GC'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./test.py", line 19, in <module>
    print(cache.wp+";"+cache.name + ";" + str(cache.type) + ";" + str(cache.favorites) + ";" + str(cache.size) + ";" + str(d))
  File "/home/sts/.local/lib/python3.6/site-packages/pycaching/util.py", line 30, in wrapper
    self.load()
  File "/home/sts/.local/lib/python3.6/site-packages/pycaching/cache.py", line 670, in load
    raise errors.LoadError()
pycaching.errors.LoadError
```

**Comment by FriedrichFroebel** [comment]
Your error does not seem to be related to the higher limits, but to PMO caches.

You have not provided any code - except from the print statement. Using it, I have been able to reproduce your problem.

In fact, it seems like there are two problems which probably have been introduced with the site redesign:

1. The detection of PMOCs seems to be broken in https://github.com/tomasbedrich/pycaching/blob/master/pycaching/cache.py#L637, `self.pm_only = root.find("section", "premium-upgrade-widget") is not None` seems like a possible fix.
2. The cache type loading in https://github.com/tomasbedrich/pycaching/blob/master/pycaching/cache.py#L648-L650 is broken as the SVG approach is now used for PMOCs, too. Therefore we can use https://github.com/tomasbedrich/pycaching/blob/master/pycaching/cache.py#L673-L675 there as well (or move these lines out of the if statement).

My test code (with the fifth cache being a PMO one at the moment):

```python
import pycaching
from pycaching import Point
from pycaching.errors import PMOnlyException

gc = pycaching.login(USER, PASSWORD)

point = Point(52.518611, 13.408333)

for cache in gc.search(point, limit=10):
    try:
        print(cache.wp + ";" + cache.name + ";" + str(cache.type) + ";" + str(cache.favorites) + ";" + str(cache.size))
    except PMOnlyException:
        print(cache.wp + ";" + cache.name + ";" + str(cache.type) + ";" + str(cache.favorites) + ";" + str(cache.size))
```

**Comment by solaristhesun** [comment]
Thanks for your help. I was able to get my script working using your suggestions.

**Comment by tomasbedrich** [comment]
Glad to hear! Can you make a PR from the solution please?

**Comment by FriedrichFroebel** [comment]
Glad to hear that this fixed the problem.

@tomasbedrich I already would have added a PR for this, but I am not familiar enough with the test code to let them know of the changes.

**Comment by tomasbedrich** [comment]
@solaristhesun New release 4.0.1 is published with fix. Please try that and let us know.
