### ISSUE TITLE
Deprecation warning running tests

### ISSUE THREAD

**Issue by FriedrichFroebel** [tomasbedrich/pycaching#133]
Running `python3 setup.py test` produces the following output:

```
running test
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
[...]
```

The cause seems to be that `setuptools.command.test.test` is used, which is now deprecated.

**Comment by tomasbedrich** [comment]
I am not against replacing this command by anything else, for example Tox as mentioned.

Based on [this great article](https://hynek.me/articles/python-app-deps-2018/) I think we might also consider introducing some more advance system, like Poetry. What do you think?

**Comment by FriedrichFroebel** [comment]
As I have no experience with Tox and not enough time to investigate, I did not yet have a look at it.

Regarding something like Poetry: In my opinion, keeping the stuff as simple and as common as possible is the best approach for now.

**Comment by FriedrichFroebel** [comment]
Obsolete with #167 and the *pytest*-based approach.
