### ISSUE TITLE
Read the Docs out of date

### ISSUE THREAD

**Issue by FriedrichFroebel** [tomasbedrich/pycaching#137]
Currently, the documentation on Read the Docs is based upon `pycaching` version 3.6.3 (commit `39aad3c2`) which is nearly two years old.

The last build attempts failed: https://readthedocs.org/projects/pycaching/builds/.

We should probably have a look at this to provide more up-to-date docs.

By the way: The year is still set to 2015 due to `docs/conf.py` (`copyright` variable) which should be updated as well.

**Comment by tomasbedrich** [comment]
Build fixed. 🕺🏼
