### ISSUE TITLE
Using a Proxy

### ISSUE THREAD

**Issue by thn80** [tomasbedrich/pycaching#165]
Is it possible to configure pycaching to use a proxy to connect to geocaching.com?

If it is not possible, would it be possible to add this in the future?

**Comment by FriedrichFroebel** [comment]
It should already be possible as `pycaching.geocaching.Geocaching` supports passing a custom session object - alternatively the underlying `requests` library should pick up the proxy data from environment values as well (if set). See the `requests` documentation for more details on how to do so: https://docs.python-requests.org/en/latest/user/advanced/#proxies
