### ISSUE TITLE
Fix docs build

### ISSUE THREAD

**Issue by tomasbedrich** [tomasbedrich/pycaching#168]
Due to `setup.py` removal, it started failing: https://readthedocs.org/projects/pycaching/builds/15273018/

(cc @FriedrichFroebel)

**Comment by FriedrichFroebel** [comment]
I am not familiar enough with `pyproject.toml` (so I am not sure if this is the best solution), but we probably have to fix the version retrieval in `docs/conf.py` (tested with `make html`):

```python
# from setup import info
import toml
configuration = toml.load('../pyproject.toml')
```

and

```python
configured_version = configuration['project']['version']
# The short X.Y version.
version = ".".join(configured_version.split(".")[:2])
# The full version, including alpha/beta/rc tags.
release = configured_version
```

I am not sure about the version handling though, as the current release `4.2.2` leads to `4.2` in the docs.

As a side note: A warning is reported about some faulty docstring:

```
/usr/local/lib/python3.8/dist-packages/pycaching/cache.py:docstring of pycaching.cache.Cache.original_location:4: WARNING: Field list ends without a blank line; unexpected unindent.
```

Another side note: Why are we using this hardcoded Python 3.5 path logic, introduced in https://github.com/tomasbedrich/pycaching/commit/f4937db4242606d2cbab23baed4337dcd22ad88f? This should not have any effect in most of the cases.

```python
# import site-packages
for package_path in Path("../lib/python3.5/site-packages").glob("*.egg"):
    sys.path.append(str(package_path.resolve()))
```

**Comment by tomasbedrich** [comment]
Fixing the way of reading project version looks like it may work. I am only afraid of using `toml`, as a dependency, which needs to be installed additionally.

Sorry, I'm not able to explain f4937db4242606d2cbab23baed4337dcd22ad88f.

What would I suggest is a bigger cut into the docs build. Maybe switching to Mkdocs? There is a [ready-made GitHub action](https://squidfunk.github.io/mkdocs-material/publishing-your-site/#with-github-actions) for publishing to GitHub pages. Does that sound interesting to you?

**Comment by FriedrichFroebel** [comment]
As far as I can tell, Python does not have direct support for reading TOML files. We might avoid this by using *tomli* instead (which is used by *flit*, an alternative could be to use the parsing from *flit-core* instead of doing it manually), but this would require that *flit* is installed on all dev systems. An alternative would be to have a dedicated version file inside the repository - either as regular text file in the root or as a `__version__`  module inside the *pycaching* module; I would prefer the module-based approach.

I am mostly familiar with Sphinx, so there is not much I can say about alternative approaches. For Python packages I prefer documentation on RTD, but this is a matter of taste as well.

**Comment by tomasbedrich** [comment]
The `__version__` based approach sounds good assuming that we are able to parse it **both** in _flit_ (pyproject.toml?) and _sphinx_.

No need to switch to Mkdocs, I just wanted to offer an alternative. If we stick with RTD, we should probably consider migration to [config file based approach](https://docs.readthedocs.io/en/stable/config-file/v2.html).

**Comment by tomasbedrich** [comment]
There seems to be another trap. :(

When I merged your issue, I end up with this: https://readthedocs.org/projects/pycaching/builds/15483386/ or https://readthedocs.org/projects/pycaching/builds/15483447/ depending on whether "Install project" is enabled or not.

![screenshot 2021-12-08 at 16 08 19](https://user-images.githubusercontent.com/4974343/145232300-67657da1-2110-43e2-8f0a-e2ba3ec45dad.jpg)

It seems right approach to me _not_ to install the package in order to be able to build it's docs. Do you think it is realistic expectation?

I know it is caused by removing `setup.py`, but I want to move forward if possible and don't stick with old approach just because RTD doesn't anything else.

**Comment by tomasbedrich** [comment]
Btw, if you register on RTD and give me your username, I can make you maintainer of the repo.

**Comment by FriedrichFroebel** [comment]
You probably cannot build the old 4.2.2 release, as this should not have the fix. But `latest` should work in theory. My RTD username is the same as for GitHub (FriedrichFroebel).

**Comment by tomasbedrich** [comment]
You have the maintainer role now. Please reconfigure the docs build according to your needs.

**Comment by FriedrichFroebel** [comment]
The docs for the master branch have been built successfully now. To fix the index page https://pycaching.readthedocs.io/, we either have to release a new version or set the default version to *latest* while the release docs are broken.

**Comment by tomasbedrich** [comment]
Good, thanks!I'd prefer if we release a new bugfix version. ---- On Thu, 09 Dec 2021 19:33:50 +0100  ***@***.***  wrote ----
The docs for the master branch have been built successfully now. To fix the index page https://pycaching.readthedocs.io/, we either have to release a new version or set the default version to latest while the release docs are broken.

**Comment by FriedrichFroebel** [comment]
With the new release, the index page is working again and this issue should be resolved.
