### ISSUE TITLE
cache.load fails

### ISSUE THREAD

**Issue by tzutzanu** [tomasbedrich/pycaching#179]
I presume some changes on the geocaching site are causing this

```
>>> geocaching = pycaching.login()
>>> gc = 'GC9N1YP'
>>> cache = geocaching.get_cache(gc)
>>> cache.load_quick()
>>> cache.name
'Desert Island Discs: Easton Corbin'
>>> cache.load()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/pycaching/cache.py", line 725, in load
    self.name = cache_details.find("h2").text
AttributeError: 'NoneType' object has no attribute 'text'
```
cache.load_quick() seems to be ok.

**Comment by FriedrichFroebel** [comment]
Thanks for the report.

From a quick look at it, only fixing the cache name retrieval will not be enough, as more places have been changed, with `_get_log_counts_from_cache_details` raising an exception as well.

Feel free to dig through the various places and submit a PR to get this library back to work.
