### ISSUE TITLE
get_trackable does not work if no type is available

### ISSUE THREAD

**Issue by nagisml** [tomasbedrich/pycaching#185]
```
trackable = geocaching.get_trackable("TB7WZD9")
trackable = geocaching.get_trackable("TB7WVN8")
```

Others are working fine.

Here the traceback

```
Traceback (most recent call last):
  File "C:\Users\xyz\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaching\util.py", line 30, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\xyz\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaching\trackable.py", line 81, in name      
    return self._name
AttributeError: 'Trackable' object has no attribute '_name'. Did you mean: 'name'?
```

My quick solution was to add

```
if type is not None:
```

in the name and type defs.

**Comment by nagisml** [comment]
fix the handling of none existign TB data in my fork and also added some TB feature.
https://github.com/nagisml/pycaching/tree/master/pycaching
Sure in not the best coding quality but it seems to work very well for me

**Comment by FriedrichFroebel** [comment]
Thanks for the report. This appears to appear for generic trackable items only.

I am not sure about your

> in the name and type defs

comment though, as just checking for `if type is not None` before calling `type.strip()` should be enough in theory.

Feel free to add a pull request fixing this issue. For further features, please open a dedicated issue beforehand and a corresponding pull request, as this makes discussing and reviewing much easier.

I would be able to send a pull request to fix this issue as well, but I am currently trying to debug why my corresponding tests fail - the login reports to be successful, but when requesting the trackable page there is no logged-in user. Given that regular loading is successful, this seems to be related to Betamax somehow.

**Comment by richardsondev** [comment]
Hey there, I ran across this exception as well and found this issue reported. I have raised a PR which fixed the exception for the TB I was looking at. Apparently this can happen for many older geocoins that aren't "Generic" as well.
