### ISSUE TITLE
Error while listing for found caches "AttributeError: 'NoneType' object has no attribute 'find_next'"

### ISSUE THREAD

**Issue by MZCacheHunter** [tomasbedrich/pycaching#188]
Hi there,

I just tried to use the example code for listing my own found caches:

```python3
import pycaching
from pycaching.log import Type as log_type

geocaching = pycaching.login()
for find in geocaching.my_finds(limit=5):
    print(find.name)
geocaching.logout()
```

Resulting in:

```python3
Traceback (most recent call last):
  File "./pycache-found-logs.py", line 8, in <module>
    for find in geocaching.my_finds(limit=5):
  File "/Users/michael/Library/Python/3.7/lib/python/site-packages/pycaching/geocaching.py", line 530, in my_logs
    current_cache = self._try_getting_cache_from_guid(guid)
  File "/Users/michael/Library/Python/3.7/lib/python/site-packages/pycaching/geocaching.py", line 499, in _try_getting_cache_from_guid
    return self.get_cache(guid=guid)
  File "/Users/michael/Library/Python/3.7/lib/python/site-packages/pycaching/geocaching.py", line 465, in get_cache
    return self._cache_from_guid(guid)
  File "/Users/michael/Library/Python/3.7/lib/python/site-packages/pycaching/geocaching.py", line 491, in _cache_from_guid
    return Cache._from_print_page(self, guid, print_page)
  File "/Users/michael/Library/Python/3.7/lib/python/site-packages/pycaching/cache.py", line 157, in _from_print_page
    **cache_info["summary"] = content.find("h2", text="Short Description").find_next("div").text
AttributeError: 'NoneType' object has no attribute 'find_next'**
```

Any help appreciated. Thanks!

**Comment by FriedrichFroebel** [comment]
Thanks for yor report.

The parser usually expects the language to be set to English. Is this set correctly in your case? Otherwise, please try to check/debug which GC code/GUID actually causes this issue (this might be another edge case as well).

**Comment by MZCacheHunter** [comment]
Sorry for the confusion caused. There seems to be something wrong with the first userid I tried in the .gc_credentials file. This user's founds cause the skript to crash, no matter which login version I use.

**Comment by FriedrichFroebel** [comment]
No problem, glad that this turned out to be a usage error instead of one with the library.

**Comment by tomasbedrich** [comment]
Still, the learning for us may be to add something like:

```python
assert page.find_by_id("some-pre-known-element").get_text() == "Expected English label", "Pycaching expects English ...."
```

What do you think, @FriedrichFroebel ?

**Comment by FriedrichFroebel** [comment]
@tomasbedrich As we are currently doing some more changes to the code anyway, we might want to tackle #136 as well. If we keep the language-independent code from `_from_print_page` and use this inside the `load_by_guid` method, this should be fixed for the cache parsing at least (I am not sure if this is an issue for the other parsers as well at the moment). See my comment there as well which includes a proposal for fixing this issue.
