### ISSUE TITLE
`Cache.load_quick()` doesn't work for non-active Geocaches

### ISSUE THREAD

**Issue by BelKed** [tomasbedrich/pycaching#209]
Groundspeak made some changes to their servers...
But, I hope they'll fix it in a moment since it makes the Browse map (old one — `/map`, not `/play/map`) partially unusable.

- **Active cache:** https://tiles.geocaching.com/map.details?i=GC8CKQQ –> Everything works fine
- **Disabled cache:** https://tiles.geocaching.com/map.details?i=GC9ZJWM –> **No data**
- **Archived cache:** https://tiles.geocaching.com/map.details?i=GC1PAR2 –> **No data**

**Comment by FriedrichFroebel** [comment]
This seems to work correctly again, thus closing it now.
