### ISSUE TITLE
get_cache Function Raising Error "Cannot Load Page: https://www.geocaching.com/seek/cdpf.aspx"

### ISSUE THREAD

**Issue by DarkOutcast6** [tomasbedrich/pycaching#211]
### Code Snippet:
`cache= geocaching.get_cache(guid="GCA9932").`

### Error:
`raise Error("Cannot load page: {}".format(url)) from e
pycaching.errors.Error: Cannot load page: https://www.geocaching.com/seek/cdpf.aspx`

**Comment by tomasbedrich** [comment]
`GCA9932` is not GUID, but rather WP (Waypoint). Simply use `geocaching.get_cache("GCA9932")`.
