### ISSUE TITLE
What type does cache.load_logbook() return and how do I turn it into a dict?

### ISSUE THREAD

**Issue by DarkOutcast6** [tomasbedrich/pycaching#215]
What type does cache.load_logbook() return and how do I turn it into a dict?

**Comment by FriedrichFroebel** [comment]
Please have a look at the official API documentation for such requests: https://pycaching.readthedocs.io/en/latest/api.html#pycaching.cache.Cache.load_logbook I will leave it as a task to the reader to convert the returned class instances to dictionaries.

**Comment by DarkOutcast6** [comment]
@FriedrichFroebel Just realized that this was not the problem I need help with. Instead it is, how do I turn the output of cache.load_logbook() into a list of Log objects?

**Comment by FriedrichFroebel** [comment]
This conversion is not specific to *pycaching*, but a general Python issue: If you really need a list, wrap it with `list(cache.load_logbook())`.
