### ISSUE TITLE
No current way to get the raw HTML cache description

### ISSUE THREAD

**Issue by DarkOutcast6** [tomasbedrich/pycaching#216]
There is no current way to get a raw HTML cache description (at least that I know)

**Comment by FriedrichFroebel** [comment]
This is correct. Feel free to submit a PR for adding a new `description_html` attribute.

**Comment by DarkOutcast6** [comment]
What library do you use to strip the geocaching website? I’ll try my best to find a way to get the raw HTML version of the description.

**Comment by DarkOutcast6** [comment]
Just made a pull request for this issue. Pull request number is #218.
It would be great if you could explain what I need to add to make it be usable for the user.

Thank you so much for the help, though!

**Comment by FriedrichFroebel** [comment]
By adding a simple test you should be able to ensure that the attribute can indeed be accessed and contains the correct data. Documentation is already present, so at least in theory this should be sufficient to make it usable.
