### ISSUE TITLE
pycaching.geocaching.search() function not working properly

### ISSUE THREAD

**Issue by DarkOutcast6** [tomasbedrich/pycaching#220]
The pycaching.geocaching.search() function not working properly.

`geocaching.search(pycaching.Point.from_string("N 34° 08.433 W 118° 28.031"),100)` raises an error displaying `AttributeError: 'NoneType' object has no attribute 'status_code'`

(assume geocaching object is previously defined)

**Comment by FriedrichFroebel** [comment]
Please provide a complete example (while omitting your credentials)  and a complete traceback. Nevertheless, this seems to be a known issue which we cannot do much about as far as I am aware (see #182).

**Comment by DarkOutcast6** [comment]
It is the same error as #182. If this indeed cannot be fixed, is there a workaround, such as a different search function to use instead of this one?

**Comment by FriedrichFroebel** [comment]
No: While there are three other search functions (see the API docs), they all internally rely on the same base method `advanced_search` as does the regular `search` method.

**Comment by BelKed** [comment]
The problem you mentioned was fixed about half a year ago in https://github.com/tomasbedrich/pycaching/pull/206.
If you want to use the fixed version of `pycaching`, you can install it with the following command:
```
pip install https://github.com/tomasbedrich/pycaching/archive/master.zip
```

**Comment by tomasbedrich** [comment]
> ```
> pip install https://github.com/tomasbedrich/pycaching/archive/master.zip
> ```

Isn’t it released?

**Comment by BelKed** [comment]
No, the latest version is 1.5 years old.

**Comment by tomasbedrich** [comment]
Shame on me. Released now.

**Comment by DarkOutcast6** [comment]
Great! Got it working! Thanks for pushing the new release!

One final problem; the documentation states that the user can input 6 arguments into the `geocaching.search()` function, but I get a code error displaying `TypeError: Geocaching.search() takes from 2 to 3 positional arguments but 8 were given` when a attempt to put more then 2 arguments. Here is the code: `geocaching.search(pycaching.Point.from_string(user_input),100,pycaching.geocaching.SortOrder.distance,False,100,pycaching.Point.from_string(user_input),None)`

![image](https://github.com/tomasbedrich/pycaching/assets/109392473/177d9522-9012-4e83-abfc-72dd507732f7)()

**Comment by FriedrichFroebel** [comment]
There is a `*` in-between, id est everything besides `point` and `limit` needs to use keywords. Additionally, you have seven parameters instead of six ones.

**Comment by DarkOutcast6** [comment]
I can't find anywhere in the documentation that described how I am supposed to get the cache objects that advanced_search() returns. How do I do this?

**Comment by FriedrichFroebel** [comment]
What exactly is your issue with the returned objects? `advanced_search` will return you `Cache` objects directly, while there might be `None` entries in-between if there have been too many requests.

**Comment by DarkOutcast6** [comment]
When using the `search()` function, it returns a `advanced_search()` object. Should this be happening? If so, how do I access the caches from the `advanced_search()` function?

**Comment by FriedrichFroebel** [comment]
No, it returns a generator of `Cache` objects:

```python3
>>> import pycaching
>>> gc = pycaching.login(..., ...)
>>> gc.search(point=pycaching.Point(48, 12), limit=100)
<generator object Geocaching.advanced_search at 0x7f02c1f45bd0>
>>> list(gc.search(point=pycaching.Point(48, 12), limit=10))
[<pycaching.cache.Cache object at 0x7f02c2efece0>, <pycaching.cache.Cache object at 0x7f02c20abb20>, <pycaching.cache.Cache object at 0x7f02c20abfd0>, <pycaching.cache.Cache object at 0x7f02c1d02f80>, <pycaching.cache.Cache object at 0x7f02c1d02d70>, <pycaching.cache.Cache object at 0x7f02c1d02ef0>, <pycaching.cache.Cache object at 0x7f02c1d02ce0>, <pycaching.cache.Cache object at 0x7f02c1d03040>, <pycaching.cache.Cache object at 0x7f02c1d02dd0>, <pycaching.cache.Cache object at 0x7f02c1d02c80>]
```
