### ISSUE TITLE
advanced_search() returning unexpected results when searching for a string

### ISSUE THREAD

**Issue by DarkOutcast6** [tomasbedrich/pycaching#221]
When I print `list(geocaching.advanced_search({"st":"some cache,"sort": "distance"},20)` to the console, it never returns the excepted results (image shown below), instead always returning the same cache objects (image shown below).

Expected Output: 
<img width="300" title="Expected Output" alt="Expected Output" src="https://github.com/tomasbedrich/pycaching/assets/109392473/1b092a91-57f2-4c67-b82c-fceb8afd7791">

Actual Output: 
<img width="240" title="Actual Output" alt="Actual Output" src="https://github.com/tomasbedrich/pycaching/assets/109392473/2e72cd4a-3a77-4bfd-b4fd-9db27c632209">

**Comment by FriedrichFroebel** [comment]
@BelKed As you tend to have more knowledge of the search itself: Can you say something about this behavior? To me it seems like the search does not really return geocaches with have a match with the string anyway.

**Comment by BelKed** [comment]
The `st` field is for location around which you want to search. The code should look something like this:

```py
list(
    geocaching.advanced_search(
        {
            "st": "Prague, Hlavní město Praha",
            "ot": "query",
            "asc": "true",
            "sort": "distance",
        },
        20,
    )
)
```

**Comment by DarkOutcast6** [comment]
Is there a field that allows me to input a name of a cache?

**Comment by BelKed** [comment]
I don't think searching for a cache name is supported on the Geocaching website for non-premium members.

**Comment by DarkOutcast6** [comment]
The strange thing is that if I search for say “The Secret Creek Cache” in the Geocaching websites search bar the according cache DOES show up and in the URL it says `st=“The Secret Creek Cache` (obviously without spaces).

**Comment by BelKed** [comment]
Well, for me it doesn't work, since the cache is too far away from my home coordinates.

**Comment by DarkOutcast6** [comment]
Huh. Well, when you search for any caches' name near your home coords, you'll find it does work. How could I implement this into my code?

**Comment by DarkOutcast6** [comment]
@BelKed That’s strange… is it possible to search for plain text in any way via pycaching?

**Comment by BelKed** [comment]
I'd say the simplest solution would be to load all the caches in the area you want to search, and then use Python to search through the loaded caches.

**Comment by DarkOutcast6** [comment]
@BelKed Oh, ok. Not the exactly what I was looking for but I guess that’ll work.
