### ISSUE TITLE
Enable squash merging?

### ISSUE THREAD

**Issue by FriedrichFroebel** [tomasbedrich/pycaching#223]
At the moment, doing a squashed merge is not possible. This might lead to a lot of irrelevant commits being pushed to the repository as in #218.

@tomasbedrich What do you think about enabling squashed merges for this repository? This would avoid cluttering the main Git history for pull requests which have lots of small revisions, for example because of new contributors.

**Comment by tomasbedrich** [comment]
Good point, enabled.
