### ISSUE TITLE
Unexpected results when searching caches from a point

### ISSUE THREAD

**Issue by SteveMan67** [tomasbedrich/pycaching#227]
With this code,
```
import pycaching
from pycaching.cache import Type
from pycaching.geo import Point

geocaching = pycaching.login("user", "pass")

point = geocaching.geocode("Tulsa")

for cache in geocaching.search(point, limit=10):
    print(cache.name)
    print(cache.location.format_decimal())
```
It gives me results like this:

>En la senda al Orlando Bravo #08
>-27.25155, -65.894667
>al crater!!!!
>-33.15815, -65.3901
>Natural Arch Viewpoint
>53.418867, -118.8868
>Kennelly's Lake Put-in
>45.288267, -77.389533
>Mirador del Tala Caido
>...

These are nowhere near Tulsa. I also tried the _geo.Point()_ module, which had the same results, which are all over the place.

**Comment by DarkOutcast6** [comment]
Please don’t include your credentials in your code.

**Comment by SteveMan67** [comment]
I tried a coordinate point as well and got the same results.

**Comment by BelKed** [comment]
No idea what is happening, but with my account, on the latest version (`0.4.4`), I'm getting these results:
```
Coney v Hot Dog
36.106, -95.9178

#1 - Places we love to go!
PMO

We All Float Down Here #2
36.09898, -95.916256

An Extra Unextraordinary Corner
36.098216, -95.914181

We All Float Down Here
36.097555, -95.917133

Ramble and Read
36.0973, -95.9212

Disc-overy!
36.0993, -95.9266333333333

Lake view
36.115067, -95.928983

Quite a Darling Place
36.122667, -95.9177

Escape!!
36.119665, -95.904155
```

**Comment by BelKed** [comment]
Oh, now I know what's happening :D

So, the default sort parameter in the `Geocaching.search()` method is `SortOrder.date_last_visited`. And as I've mentioned in https://github.com/tomasbedrich/pycaching/issues/204, for basic members only `SortOrder.distance` works.

So your account probably isn't a basic member. And the caches you get from the code are sorted by `SortOrder.date_last_visited`. I'll create a PR to fix this soon :)

For now, there's a working code that gives the expected results:

```py
import pycaching
from pycaching.geocaching import SortOrder

geocaching = pycaching.login("login", "password")

point = geocaching.geocode("Tulsa")

for cache in geocaching.search(point, limit=10, sort_by=SortOrder.distance):
    print(cache.name)
    print(cache.location.format_decimal())
```

**Comment by FriedrichFroebel** [comment]
Given the comment by @BelKed, it seems like this is just some usage issue I am and going to close this as resolved.
