### ISSUE TITLE
Docs build is failing

### ISSUE THREAD

**Issue by tomasbedrich** [tomasbedrich/pycaching#229]
See: https://readthedocs.org/projects/pycaching/builds/22691097/

We likely need to add a new config file into the project. See: https://blog.readthedocs.com/migrate-configuration-v2/

We can also consider switching away from a Webhook triggering the docs build.

**Comment by FriedrichFroebel** [comment]
We should already use version 2: https://github.com/tomasbedrich/pycaching/blob/master/.readthedocs.yaml

**Comment by FriedrichFroebel** [comment]
I have just submitted #230 which should fix this issue by syncing the format with the latest docs.

**Comment by tomasbedrich** [comment]
Sorry to oversee the file in the repo. 🙈 thanks for the PR

**Comment by FriedrichFroebel** [comment]
We still have a dependency issue: https://docs.readthedocs.io/en/stable/config-file/v2.html#packages probably needs to be expanded to include `sphinx_rtd_theme` as an extra in the `pyproject.toml` file: https://readthedocs.org/projects/pycaching/builds/22752077/

I might have a look at this later as well, but at least our basic configuration file seems to be valid now.

**Comment by FriedrichFroebel** [comment]
Finally fixed in #232.
