### ISSUE TITLE
Archive Log Type Can Be 5 or 6

### ISSUE THREAD

**Issue by GeoTime61** [tomasbedrich/pycaching#234]
I tried to process a cache, but got an error: Unknown log type '6'. It appears that there are two possible Archive log types - 5 or 6. The simple program below shows the error. GC code GCHK3P works fine. GCADFC fails with the log type '6' error. It looks like log.py can handle two different IDs for a single log type. Is it as simple as adding '6' to from_filename()?

```
import pycaching

geocaching = pycaching.login()

cache = geocaching.get_cache("GCHK3P")  # Archive type 5
print(cache.found)

cache = geocaching.get_cache("GCADFC")  # Archive type 6
print(cache.found)  # Fails with "pycaching.errors.ValueError: Unknown log type '6'."

geocaching.logout()
```

**Comment by FriedrichFroebel** [comment]
Feel free to open a corresponding PR.

**Comment by DarkOutcast6** [comment]
#235

**Comment by GeoTime61** [comment]
I don't know anything about GitHub, but I did my best to create a pull request with the change and a simple test.

Following the steps in CONTRIBUTING:
"isort ." worked.
"black ." worked.
"flake8" failed - AttributeError: 'EntryPoints' object has no attribute 'get'
"pytest test" (had to add " test") failed - FAIL Required test coverage of 90% not reached. Total coverage: 89.90%

Maybe you can tell me what I did wrong or help me fix the errors.
