### ISSUE TITLE
Parsing cache logs

### ISSUE THREAD

**Issue by tomasbedrich** [tomasbedrich/pycaching#30]
Use this URL: http://www.geocaching.com/seek/geocache.logbook?tkn=2XTN3PAW6BOQF344SAYTREXPUPL54A7EI3773SIWYGHUZM3TB6GMCU45WFOOO2DXP5PFNRLZ26W2BHCYH3V3GLKCTDH6MAPYNNTJFKBNFYGUDTVO6SSIX66LQPKDGSU2L5UZ2CH5JF7VH3GXKZKN2WNL24&idx=2&num=10&sp=false&sf=false&decrypt=false
The above is just XHR-requested URL from http://www.geocaching.com/seek/cache_logbook.aspx?guid=182a3463-e46e-4401-8697-3ad3ac2a1a42

**Comment by forslund** [comment]
I'm working on this and have gotten parts of the code down. should I keep all the log information (23 fields per log entry) or should I strip out the most interesting fields?
