### ISSUE TITLE
Favorite points for event caches

### ISSUE THREAD

**Issue by tomasbedrich** [tomasbedrich/pycaching#36]
For Event-caches there is no field for favorite points so the code fails.

-- Uwe Zimmermann

**Comment by forslund** [comment]
This seems to work for me (revision f517e3789617b059bdf6a558a8e3cc242cf6f063)

Tested with:
```python
c2 = gc.load_cache('GC5ZDWB')
print(c2.favorites)
```
Above code produced
```
0
```
It's sort of correct but maybe it should be None or something similar instead?

**Comment by tomasbedrich** [comment]
I agree, this is correct - keep it `int` to be consistent.
