### ISSUE TITLE
Retrieve original coordinates for mystery caches with corrected coordinates

### ISSUE THREAD

**Issue by tomasbedrich** [tomasbedrich/pycaching#37]
The original coordinates are located in the javascript data block as "oldLatLng".

-- Uwe Zimmermann

**Comment by forslund** [comment]
Do we have the GC-code for a cache that has this issue?

**Comment by tomasbedrich** [comment]
It is more feature request than bug. You can edit the coordinates for every mystery and multi cache (the pencil button next to the coordinates, see attached image).

<img width="1046" alt="snimek obrazovky 2016-01-18 v 15 03 05" src="https://cloud.githubusercontent.com/assets/4974343/12393229/b03602a0-bdf4-11e5-941c-bb9feda3a39f.png">

When you load the cache using pycaching, only the new coordinates will be parsed. I think the point of Uwe's suggestion was to retrieve the original coordinates too. Currently they are not available from the pycaching point of view.

**Comment by tomasbedrich** [comment]
Are you interested in solving this?

**Comment by forslund** [comment]
Yes, I didn't have time looking into it during the week but expect a pull
request tonight or tomorrow morning.
Den 23 jan 2016 14:21 skrev "Tomáš Bedřich" <notifications@github.com>:

**Comment by tomasbedrich** [comment]
Don't hurry, I just want to know.
