### ISSUE TITLE
Premium caches: retrieve some details

### ISSUE THREAD

**Issue by lpefferkorn** [tomasbedrich/pycaching#43]
At the moment, when using `load_cache()` to retrieve a premium cache details with a free account, a  `PMOnlyException` exception is thrown.
It would be great to fetch the available cache informations:

* name
* size
* author
* difficulty 
* terrain

Thank you!

**Comment by tomasbedrich** [comment]
Thank you for you suggestion. I will include this feature in version 3.3.1.

In the meantime, use can use something like this:

```python
try:
   c = load_cache(...)
except PMOnlyException:
   c = load_cache_quick(...)

**Comment by lpefferkorn** [comment]
Thanks!

**Comment by tomasbedrich** [comment]
You are welcome. ;) Feel free to contribute next time.
