### ISSUE TITLE
Create CONTRIBUTING.md

### ISSUE THREAD

**Issue by tomasbedrich** [tomasbedrich/pycaching#45]
Describe:
- [x] style guide (mention line length exception)
- [x] test running and required coverage
- [x] "contributors friendly" issues
- [x] using double quotes
- [x] create `.editorconfig` file

**Comment by forslund** [comment]
Maybe add policy on importing modules. I personally have tried to limit importing to bare minimum when contributing.

Something along the line of 
Standard library is nearly always ok
Third-party that can be installed from the cheese shop is ok if there is very good reason
Third-party modules that has to be installed manually should never be required

**Comment by tomasbedrich** [comment]
Good idea @forslund, thanks.

**Comment by tomasbedrich** [comment]
Closed by 729d44d9e2f1c7c7fb08e6d809d89e31a45823ff.
