### ISSUE TITLE
Beautiful Soup warning

### ISSUE THREAD

**Issue by filipek92** [tomasbedrich/pycaching#47]
Warning reported on WIndows x64:

> Python 3.5.0 (v3.5.0:374f501f4567, Sep 13 2015, 02:16:59) [MSC v.1900 32 bit (Intel)] on win32
> Type "help", "copyright", "credits" or "license" for more information.
> import pycaching
> g = pycaching.login("user","pass")

> C:\Program Files (x86)\Python 3.5\lib\site-packages\bs4\__init__.py:166: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html.parser"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

> To get rid of this warning, change this:
BeautifulSoup([your markup])
to this:
BeautifulSoup([your markup], "html.parser") markup_type=markup_type))

**Comment by tomasbedrich** [comment]
To be solved by removing dependency on MechanicalSoup and changing `Geocaching_request` method...

**Comment by tomasbedrich** [comment]
@filipek92 please try again and let me know if it works now

**Comment by filipek92** [comment]
Now, it works ok.
