### ISSUE TITLE
sphinxdoc/source/conf.py generates lots of lint errors

### ISSUE THREAD

**Issue by forslund** [tomasbedrich/pycaching#55]
when running ```python3 setup.py lint```

I get a lot of errors in ```./sphinxdoc/source/conf.py```

 The errors are mostly
```  E265 block comment should start with '# '```
and a couple of unused imports.

should the file (or maybe the entire sphinxdoc directory) be excluded from lint or should the errors be corrected?

**Comment by tomasbedrich** [comment]
You are right, this config file should be excluded. I am sure it works for me, but don't know why not for you... I will look at it soon.

**Comment by forslund** [comment]
Could it be some version of something or other? Is there anything I can check? In the time being I'll just add an exclude path to setup.cfg

**Comment by tomasbedrich** [comment]
That's really strange. The `docs` is already [in excluded path](https://github.com/tomasbedrich/pycaching/blob/master/setup.cfg#L7). But you wrote the error comes from `./sphinxdoc/...` directory. Do you know where this directory comes from? I can't find it anywhere in the repo.

**Comment by forslund** [comment]
Ok, this is my bad. I was playing around with sphinx before you added it and it seems my old files were still around. Sorry for the false alarm.
