### ISSUE TITLE
Allow tracking codes besides trackable id

### ISSUE THREAD

**Issue by FriedrichFroebel** [tomasbedrich/pycaching#61]
Maybe it's a good idea to allow tracking codes besides the trackable id. Currently there seems to be a check for the first two characters of the given code and therefore inserting a tracking code fails.
The URL is the same as far as I know.

**Comment by tomasbedrich** [comment]
Hello Friedrich, thanks for your idea. Would you please consider contributing? Every bit counts. It could be as easy as changing a `Trackable.load` method.

**Comment by FriedrichFroebel** [comment]
Changed with https://github.com/tomasbedrich/pycaching/pull/63.
