### ISSUE TITLE
Enable request for trackable routes

### ISSUE THREAD

**Issue by FriedrichFroebel** [tomasbedrich/pycaching#62]
When accessing a trackable page via web browser I am able to download the route of the specified trackable as a KML file. Could be very helpful to enable an automated download of these routes (saving them as files would be enough from my point of view).
Seems like the download link could be parsed using `id="ctl00_ContentBody_lnkGoogleKML"`.

**Comment by tomasbedrich** [comment]
Okay, I think we can do it this way:

- [ ] parse the download link you suggested in the `Trackable.load` method, store it as an instance attribute
- [ ] create `Trackable.get_KML` method which would use this attribute to make a HTTP request and return a KML as a `str`
- [ ] write tests and docs

Would you consider helping with that, please?

**Comment by FriedrichFroebel** [comment]
I will have a look at this as soon as possible.
Unfortunately I could not get the liner working - it raises some `IndexError: list index out of range`.

**Comment by tomasbedrich** [comment]
Can you please create a separate issue for that? It would be best, if you could include a full error message.

**Comment by tomasbedrich** [comment]
Hello @FriedrichFroebel, what do you think – are you going to solve this issue? It is the last release blocker for version 3.6.

**Comment by FriedrichFroebel** [comment]
I am currently on vacation, so this would probably take some days until
I will have a look at this.

**Comment by tomasbedrich** [comment]
Okay, have a nice vacation! 😉  I will wait until the 10th of September, so please inform me about the progress as you get back.

**Comment by FriedrichFroebel** [comment]
Just found some time to have a look at this. I currently get stuck when trying to test my current implementation as I get `AttributeError: 'Trackable' object has no attribute 'get_KML()'` after running the setup script after my changes and then trying to use some small script:
```
import pycaching
g = pycaching.login(...)  # credentials removed
trackable = g.get_trackable("TB3ZGT2")
print(trackable.name)  # works
trackable.get_KML()  # throws error
```

**Comment by tomasbedrich** [comment]
I think the problem is the setup script you run again. You should only need to setup your enviroment once. If you need to test new features, either write new tests or use a test script named `test.py` inside the root of the project, which is ignored by GIT.

**Comment by FriedrichFroebel** [comment]
This way the problem has gone away.

Another problem: The BeautifulSoup4 module changes the XML tags of the KML file to lowercase which seems to be a problem for Google Earth when trying to import it there.

**Comment by tomasbedrich** [comment]
Do you think it is necessary to parse a XML using a BeautifulSoup? If you pass an optional argument `expect="raw"` to the `Geocaching._request()` method, you will get the raw response as a [requests.Response](http://docs.python-requests.org/en/master/api/#requests.Response) object. 😉

**Comment by FriedrichFroebel** [comment]
I've updated the PR according this.

**Comment by tomasbedrich** [comment]
Thank you!
