### ISSUE TITLE
IndexError when using linter

### ISSUE THREAD

**Issue by FriedrichFroebel** [tomasbedrich/pycaching#64]
When calling `python setup.py lint` after cloning the repo (as described in CONTRIBUTING.rst), I get some error messages.

Calling `flake8 ---version` displays `2.6.2 (pycodestyle: 2.0.0, pyflakes: 1.2.3, mccabe: 0.5.2) CPython 3.6.0a3 on Windows`.

The error message which is repeated some times:
```
running lint
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python\lib\multiprocessing\spawn.py", line 106, in spawn_main
    exitcode = _main(fd)
  File "C:\Python\lib\multiprocessing\spawn.py", line 115, in _main
    prepare(preparation_data)
  File "C:\Python\lib\multiprocessing\spawn.py", line 226, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Python\lib\multiprocessing\spawn.py", line 278, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Python\lib\runpy.py", line 254, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Python\lib\runpy.py", line 93, in _run_module_code
    with _TempModule(mod_name) as temp_module, _ModifiedArgv0(fname):
  File "C:\Python\lib\runpy.py", line 54, in __enter__
    self._saved_value = sys.argv[0]
IndexError: list index out of range
```

**Comment by tomasbedrich** [comment]
Strange, everything works fine on my machine, when trying to setup the repo the same way.

I have added a virtualenv setup guide to `CONTRIBUTING.rst`. Can you please try it again with these new steps?

One more question – are you sure that you are using Python **>= 3.3**?

**Comment by FriedrichFroebel** [comment]
Setting up a virtual environment does not cause any problems in the first step, but with `source bin/activate` I get an error message by the Windows command line saying that the command _source_ could not be found.

Calling `python --version` says `Python 3.6.0a3` which should meet the >=3.3 requirement.

**Comment by tomasbedrich** [comment]
Okay, can you please try out [this branch](/tomasbedrich/pycaching/tree/issue-64)? I suspect the Windows implementation of a `runpy`module.

**Comment by weinshec** [comment]
@FriedrichFroebel I think you cannot activate the virtualenv like this on windows... There is no such thing as `source` which is why the command line complains about that. According to the [virtualenv documentation](https://virtualenv.pypa.io/en/stable/userguide/) you should use

> On Windows, the equivalent activate script is in the Scripts folder:
> 
> \>`\path\to\env\Scripts\activate`
> 
> And type `deactivate` to undo the changes.
>
> Based on your active shell (CMD.exe or Powershell.exe), Windows will use either activate.bat or
> activate.ps1 (as appropriate) to activate the virtual environment. If using Powershell, see the notes
> about code signing below.

**Comment by FriedrichFroebel** [comment]
I gave it another try and finally could activate the virtualenv. With the change inside the setup file concerning `sys.argv` the error messages have disappeared.
