### ISSUE TITLE
trackable.post_log seems to work quite randomly

### ISSUE THREAD

**Issue by mrummuka** [tomasbedrich/pycaching#71]
Hi,
I've experimented with the library for a while and I think I observed with some random behaviour with trackable.post_log. To me, it seems to work on/off,  i.e. sometimes logging tbs is successful and some other time  not. 

Has anyone noticed similar behaviour? I think I can give an example of at least couple of TBs (TB5ZBY7) which fail to log.
By increasing log level I get

> DEBUG:requests.packages.urllib3.connectionpool:"GET /track/details.aspx?tracker=XXXXXX HTTP/1.1" 200 68978
> DEBUG:requests.packages.urllib3.connectionpool:"GET /track/log.aspx?wid=a9c1fca6-4b8c-4235-9ed4-a7cb7ab9257d&c=XXXXXX HTTP/1.1" 200 58194
> DEBUG:requests.packages.urllib3.connectionpool:"POST /track/log.aspx?wid=a9c1fca6-4b8c-4235-9ed4-a7cb7ab9257d&c=XXXXXX HTTP/1.1" 200 58151

when it fails and

> DEBUG:requests.packages.urllib3.connectionpool:"GET /track/details.aspx?tracker=XXXXXX HTTP/1.1" 200 69202
> DEBUG:requests.packages.urllib3.connectionpool:"GET /track/log.aspx?wid=a9c1fca6-4b8c-4235-9ed4-a7cb7ab9257d&c=XXXXXX HTTP/1.1" 200 58194
> DEBUG:requests.packages.urllib3.connectionpool:"POST /track/log.aspx?wid=a9c1fca6-4b8c-4235-9ed4-a7cb7ab9257d&c=XXXXXX HTTP/1.1" 302 158
> DEBUG:requests.packages.urllib3.connectionpool:"GET /track/log.aspx?LogReferenceCode=YYYYYYYY HTTP/1.1" 200 53937

when it succeeds. TB logging code is hidden in above but I used the same one both times - PM if you wish to test this.

**Comment by tomasbedrich** [comment]
Hello, thanks for your report. I would not like to spam some trackable with logs for testing this and it appears that you work more often with trackables than me. If so, can you please try to debug it a little bit more? First, we will certainly need a dump of POSTed data.

**Comment by mrummuka** [comment]
Hi, will do.  I've actually been spamming some trackables (ugh) while fighting with this 8-}. If writing note to your own trackables worked it might be easier to debug this without causing much inconvenience for others (exception thrown there,  will include that as well later)..

**Comment by tomasbedrich** [comment]
Hello again, I have finally done some debugging and changes in logging methods. Can you please test the branch `issue-71`?

Also, I have grabbed one of your TBs while testing, so please grab it back.
