### ISSUE TITLE
Iterating trough .Cache object raises ValueError in most cases

### ISSUE THREAD

**Issue by tompavelka** [tomasbedrich/pycaching#79]
ValueError points to line 1112 in cache.py:

`in from_string
    return cls(name)
  File "/usr/lib/python3.6/enum.py", line 291, in __call__
    return cls.__new__(cls, value)
  File "/usr/lib/python3.6/enum.py", line 533, in __new__
    return cls._missing_(value)
  File "/usr/lib/python3.6/enum.py", line 546, in _missing_
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: 'střední' is not a valid Size` 

get_cache method works ok.

T. Pavelka

**Comment by tompavelka** [comment]
If lines 248-250 are in geocaching. py are commented out, it works again (.Cache object than misses attributes size, difficulty an terrain.

**Comment by tomasbedrich** [comment]
When I look at the error (`ValueError: 'střední' is not a valid Size`), it is probably because you have your Geocaching account language set to Czech. Until somebody will take a look at this, you can temporary try to fix it by switching to English.
