### ISSUE TITLE
Log type '24' is not recognized

### ISSUE THREAD

**Issue by jarhill0** [tomasbedrich/pycaching#84]
Load any cache as `c` and run the following:

```
for l in c.load_logbook():
    print('{} by {} ({}):\n\n{}'.format(l.type, l.author, l.visited, l.text))
```

All logs will output successfully, until the end, when the following exception is raised: `pycaching.errors.ValueError: Unknown log type '24'.`.

By visiting https://www.geocaching.com/images/logtypes/24.png, one can see that log type '24' is 'Publish Listing'. Can this be added?

**Comment by tomasbedrich** [comment]
Glad to see your effort in debugging a pycaching. 👍 PR with fix is welcome!
