### ISSUE TITLE
cache.found = user has left comment  

### ISSUE THREAD

**Issue by Wlodarski** [tomasbedrich/pycaching#89]
If a user posts a DNF (didn't not find) or a note on geocaching.com, pychaching reports that cache is if it was "found" by that user.

**Comment by Wlodarski** [comment]
By replacing line 630 in cache.py by 

>  self.found = found and ("Found It!" in found.text or "Attended" in found.text) or False

the script works for me

**Comment by jarhill0** [comment]
For that matter, there's no need to have a tailing `or False`. The line could be just `self.found = found and ("Found It!" in found.text or "Attended" in found.text)`.

**Comment by Wlodarski** [comment]
Fix worked. Thank you.
