### ISSUE TITLE
error while installing 

### ISSUE THREAD

**Issue by sDor5** [tomasbedrich/pycaching#97]
I tried installing the package, and get the following error:

```
Collecting pycaching
  Using cached https://files.pythonhosted.org/packages/e1/b8/dab5c9432d1af40f03fce718d05fc8fdc1588f88f724871d208460fde535/pycaching-3.6.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\MYUSERNAME\AppData\Local\Temp\pycharm-packaging\pycaching\setup.py", line 43, in <module>
        with (root / "requirements.txt").open(encoding="utf-8") as f:
      File "C:\Python36\lib\pathlib.py", line 1164, in open
        opener=self._opener)
      File "C:\Python36\lib\pathlib.py", line 1018, in _opener
        return self._accessor.open(self, flags, mode)
      File "C:\Python36\lib\pathlib.py", line 390, in wrapped
        return strfunc(str(pathobj), *args)
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\MYUSERNAME\\AppData\\Local\\Temp\\pycharm-packaging\\pycaching\\requirements.txt'
    
    ----------------------------------------

Command "python setup.py egg_info" failed with error code 1 in C:\Users\MYUSERNAME\AppData\Local\Temp\pycharm-packaging\pycaching\

```

this happened on my friend's computer too. Has something maybe broken in the package files? am I doing it wrong? any workaround?

Thanks

**Comment by tomasbedrich** [comment]
Thank you for a notice, it was caused by a missing wheel package on pypi. I have [uploaded the package](https://pypi.org/project/pycaching/3.6.3/#files) and it should work now.

However, this issue revealed a problem with "sdist" distribution, which is missing `requirements.txt` in the archive. I will solve it in the next release.

**Comment by sDor5** [comment]
Thanks!


On Aug 8, 2018 at 4:05 PM, <Tomáš Bedřich <notifications@github.com>>
wrote:

Thank you for a notice, it was caused by a missing wheel package on pypi. I
have uploaded the package <https://pypi.org/project/pycaching/3.6.3/#files>
and it should work now.

However, this issue revealed a problem with "sdist" distribution, which is
missing requirements.txt in the archive. I will solve it in the next
release.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/tomasbedrich/pycaching/issues/97#issuecomment-411382142>,
or mute the thread
